services:

  fastproject_database:
    image: postgres:16
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fast_project:
    build: .
    image: fast_project
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - fastproject_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastproject_database:5432/app_db

volumes:
  pgdata: