"""create todos table

Revision ID: 272e30f1b315
Revises: f4406273d7e9
Create Date: 2026-02-21 15:29:04.175174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272e30f1b315'
down_revision: Union[str, Sequence[str], None] = 'f4406273d7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    def upgrade() -> None:
     """Upgrade schema."""
     # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "draft",
                "todo",
                "doing",
                "done",
                "trash",
                name="todostate"
            ),
            nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

def downgrade() -> None:
   def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todos")
    sa.Enum(
        "draft",
        "todo",
        "doing",
        "done",
        "trash",
        name="todostate"
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
