"""implemantaçao do created_at e updated_at

Revision ID: 552d64b66cf6
Revises: 272e30f1b315
Create Date: 2026-02-24 23:40:22.914413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552d64b66cf6'
down_revision: Union[str, Sequence[str], None] = '272e30f1b315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=True))

    
    op.execute("UPDATE todos SET created_at = CURRENT_TIMESTAMP")
    op.execute("UPDATE todos SET updated_at = CURRENT_TIMESTAMP")

   
    op.alter_column('todos', 'created_at', nullable=False)
    op.alter_column('todos', 'updated_at', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
